# Python Review

Short Reiew about some core concepts in Python exemplified by objects in the Numpy library.

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our program. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computin in Python
- many of libraries use NumPy arrays as their building blocks
- computation on NumPy objects are optimized for speed and memory usage. 

Let's import NumPy with its **standard abbreviation** `np`:

In [2]:
import numpy as np

## Variables

**variables:** a name we assign to a particular object in python

Example: 

In [3]:
# Assign a small array variable a
a = np.array([ [1, 1, 2], [3, 5, 8] ])

To view a variable's value from our Jupter notebook:

In [4]:
# run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake_case` for naming variables.

This is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `myVariable`, 
PEP 8- Style Guide for Python Code recommends `snake_case`. 

**Remember that variable names should both be descriptive and consise!**

## Objects

**object:** (informatlly speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding anew column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use the word variable and object interchangeably. 

## Types

Every Object in Python has a **type**, the type tells us what kind of object we have.
We can also call the type of an object, the **class** of an object. So class and object both mean what kind of object we have. 

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


In [7]:
# See the type/class of a variable/object by using the `type` function
type(a)

numpy.ndarray

In [14]:
np.ndarray

numpy.ndarray

In [15]:
print(a[0,0])

type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer type `int`.

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number. 

Check-in access the value 5 in array `a`

In [17]:
print(a[1,1])

5


## Functions

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**

In the course we'll be using argument and parameter interchangeably. But they do have slightly different meanings. 

We can ask for info about what a function does by executing `?` followed by the function name:

In [19]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or a class, or module) works.

Notice is that there are different types of arguments inside the function's paranthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments *you* have to specify for the function to work

- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the paranthesis () in the form `optional_arugment = default_value`

Example

`end` is a parameter in `print` with default value a new line
We can pass another value `:)` to this parameter so that it finishes the line with `:-)` instead:

In [21]:
print('Change the end parameter', end = ':-)')

Change the end parameter:-)

## Attributes and methods 

An Object in Python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it.
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself. 

## Check-in

Make a diagram like the cat one, for a class `fish`. What are its attributes and methods? 

Example: 

NumPy arrays have many methods and attribtues. For exampel:

In [22]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [23]:
# T is an example of an attribute, it returns the tranpose of the array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [24]:
type(a.T)

numpy.ndarray

In [27]:
# shape another attribute tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [30]:
# ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data type. 

Some examples of methods. 

In [31]:
# The min method returns the minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [32]:
# Run min method without axis
a.min()

1

Remember, methods are **functions** associated with an object. We can confirm this! 

In [33]:
# method tolist() transform array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [34]:
type(a.tolist)

builtin_function_or_method

# Exercise

1. Read the `print` function help. What is the type of arguments `sep` `?` Is this a default or non-default argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the strong 99. 

3. Use your variables to print 77%99%77 by changing the value of one of the default arguments in `print` 

In [35]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [40]:
b = 77
c = '99'

In [41]:
print(b,c,b, sep = "%")

77%99%77
