# Python Review

Short Reiew about some core concepts in Python exemplified by objects in the Numpy library.

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our program. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computin in Python
- many of libraries use NumPy arrays as their building blocks
- computation on NumPy objects are optimized for speed and memory usage. 

Let's import NumPy with its **standard abbreviation** `np`:

In [1]:
import numpy as np

## Variables

**variables:** a name we assign to a particular object in python

Example: 

In [2]:
# Assign a small array variable a
a = np.array([ [1, 1, 2], [3, 5, 8] ])

To view a variable's value from our Jupter notebook:

In [3]:
# run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
